// test/e2e/scenarios/local-only/local-only.test.ts
import { runScenariosFromFile } from '../_runner/scenario-runner.ts';

const CONFIG_PATH =
  process.env.SCENARIO_CONFIG ?? 'test/e2e/scenarios/local-only/config/tests.json';

// vitest registers describes/its generated by the runner at import time
await runScenariosFromFile(CONFIG_PATH);
